version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: micropay_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: web3_micropay_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - micropay_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d web3_micropay_dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: micropay_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - micropay_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  micropay_postgres_data:
  micropay_redis_data:
